import {
  LayoutDashboard,
  Users2,
  Users,
  List,
  Filter,
  Tag,
  UserMinus,
  Gauge,
  Megaphone,
  Mail,
  LayoutTemplate,
  FileText,
  SquareStack,
  WandSparkles,
  Clock,
  FlaskConical,
  Calendar,
  Workflow,
  Route,
  MousePointerClick,
  GitFork,
  BookOpen,
  Send,
  Smartphone,
  MessageCircle,
  Bell,
  AppWindow,
  Code,
  Server,
  FileCode,
  ScrollText,
  Inbox,
  MessageSquare,
  MessagesSquare,
  ShieldCheck,
  Globe,
  Lock,
  Network,
  Flame,
  Target,
  ShieldAlert,
  MailCheck,
  Briefcase,
  Handshake,
  KanbanSquare,
  CheckSquare,
  Building2,
  Activity,
  Funnel,
  PanelTop,
  ClipboardList,
  ShoppingCart,
  Store,
  Package,
  ShoppingBag,
  BadgePercent,
  Image,
  LayoutGrid,
  Palette,
  Crop,
  Files,
  BarChart3,
  LineChart,
  Columns2,
  DollarSign,
  FileBarChart,
  Sparkles,
  PenLine,
  Lightbulb,
  Type,
  HeartPulse,
  Database,
  Boxes,
  Plug,
  Blocks,
  Webhook,
  KeyRound,
  Plug2,
  Settings,
} from "lucide-react";

export const projectNav = [
  { title: "Overview", icon: LayoutDashboard },
  {
    title: "Audience",
    icon: Users2,
    subItems: [
      { title: "Contacts", icon: Users },
      { title: "Lists", icon: List },
      { title: "Segments", icon: Filter },
      { title: "Tags & Fields", icon: Tag },
      { title: "Lead Scoring", icon: Gauge },
      { title: "Suppression", icon: UserMinus },
    ],
  },
  {
    title: "Campaigns",
    icon: Megaphone,
    subItems: [
      { title: "All Campaigns", icon: Mail },
      { title: "Email Builder", icon: LayoutTemplate },
      { title: "Templates", icon: FileText },
      { title: "Content Blocks", icon: SquareStack },
      { title: "Personalization", icon: WandSparkles },
      { title: "A/B Testing", icon: FlaskConical },
      { title: "Send-Time Optimization", icon: Clock },
      { title: "Calendar", icon: Calendar },
    ],
  },
  {
    title: "Automations",
    icon: Workflow,
    subItems: [
      { title: "Workflows", icon: Workflow },
      { title: "Journeys", icon: Route },
      { title: "Triggers", icon: MousePointerClick },
      { title: "Conditions & Goals", icon: GitFork },
      { title: "Recipes", icon: BookOpen },
    ],
  },
  {
    title: "Channels",
    icon: Send,
    subItems: [
      { title: "Email", icon: Mail },
      { title: "SMS", icon: Smartphone },
      { title: "WhatsApp", icon: MessageCircle },
      { title: "Push", icon: Bell },
      { title: "In-App", icon: AppWindow },
    ],
  },
  {
    title: "Transactional",
    icon: Code,
    subItems: [
      { title: "Email API", icon: Code },
      { title: "SMTP Relay", icon: Server },
      { title: "Transactional Templates", icon: FileCode },
      { title: "Inbound Routing", icon: Inbox },
      { title: "Message Logs", icon: ScrollText },
    ],
  },
  {
    title: "Deliverability",
    icon: ShieldCheck,
    subItems: [
      { title: "Sending Domains", icon: Globe },
      { title: "Authentication", icon: Lock },
      { title: "Dedicated IPs", icon: Network },
      { title: "IP Warmup", icon: Flame },
      { title: "Inbox Placement", icon: Target },
      { title: "Blocklist Monitor", icon: ShieldAlert },
      { title: "Email Validation", icon: MailCheck },
    ],
  },
  {
    title: "CRM",
    icon: Briefcase,
    subItems: [
      { title: "Deals", icon: Handshake },
      { title: "Pipelines", icon: KanbanSquare },
      { title: "Tasks", icon: CheckSquare },
      { title: "Companies", icon: Building2 },
      { title: "Activity", icon: Activity },
    ],
  },
  {
    title: "Inbox",
    icon: Inbox,
    subItems: [
      { title: "Conversations", icon: MessageSquare },
      { title: "SMS Inbox", icon: Smartphone },
      { title: "WhatsApp Inbox", icon: MessageCircle },
      { title: "Live Chat", icon: MessagesSquare },
    ],
  },
  {
    title: "Acquisition",
    icon: Funnel,
    subItems: [
      { title: "Forms", icon: FileText },
      { title: "Landing Pages", icon: PanelTop },
      { title: "Popups", icon: AppWindow },
      { title: "Surveys", icon: ClipboardList },
      { title: "Source Tracking", icon: MousePointerClick },
    ],
  },
  {
    title: "Commerce",
    icon: ShoppingCart,
    subItems: [
      { title: "Stores", icon: Store },
      { title: "Products", icon: Package },
      { title: "Orders", icon: ShoppingBag },
      { title: "Abandoned Carts", icon: ShoppingCart },
      { title: "Coupons", icon: BadgePercent },
      { title: "Recommendations", icon: WandSparkles },
    ],
  },
  {
    title: "Content",
    icon: Image,
    subItems: [
      { title: "Asset Library", icon: LayoutGrid },
      { title: "Brand Kit", icon: Palette },
      { title: "Image Editor", icon: Crop },
      { title: "Files", icon: Files },
    ],
  },
  {
    title: "Reporting",
    icon: BarChart3,
    subItems: [
      { title: "Dashboards", icon: LineChart },
      { title: "Campaign Comparison", icon: Columns2 },
      { title: "Engagement", icon: MousePointerClick },
      { title: "Attribution", icon: DollarSign },
      { title: "Deliverability Reports", icon: MailCheck },
      { title: "Custom Reports", icon: FileBarChart },
    ],
  },
  {
    title: "AI Assistant",
    icon: Sparkles,
    subItems: [
      { title: "Campaign Brief", icon: PenLine },
      { title: "Copy Generator", icon: Lightbulb },
      { title: "Subject Lines", icon: Type },
      { title: "Segment Suggestions", icon: Filter },
      { title: "Campaign Health", icon: HeartPulse },
    ],
  },
  {
    title: "Data",
    icon: Database,
    subItems: [
      { title: "Custom Objects", icon: Boxes },
      { title: "Catalogs", icon: BookOpen },
      { title: "Event Tracking", icon: Activity },
      { title: "Warehouse Sync", icon: Database },
    ],
  },
  {
    title: "Integrations",
    icon: Plug,
    subItems: [
      { title: "Apps", icon: Blocks },
      { title: "Webhooks", icon: Webhook },
      { title: "API Keys", icon: KeyRound },
    ],
  },
  { title: "Settings", icon: Settings, hasSubmenu: true },
];

export const settingsNav = [
  { title: "General", icon: Settings },
  { title: "Team & Roles", icon: Users2 },
  { title: "Approvals", icon: ShieldCheck },
  { title: "Branding", icon: Palette },
  { title: "Billing", icon: DollarSign },
  { title: "Connections", icon: Plug2 },
  { title: "Advanced", icon: Activity },
];
